name: nutrithink_dummy
description: Dummy Flutter skeleton for MDPI code availability.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

flutter:
  uses-material-design: true
